### ISSUE TITLE
Suggestion: more robust error code / message handling

### ISSUE THREAD

**Issue by gRegorLove** [stymiee/authnetjson#3]
For transactions with response codes 2-4 I'm interested in logging the error/message code and text. `AuthnetJsonResponse::getErrorCode()` and `getErrorText()` is basically what I want, but those are conditional on `isError()`. 

In some of the transactions I'm seeing, the Authorize.net API call was successful, but the transaction failed (card declined). So the above functions return empty strings, even though there is a `transactionResponse->errors` or `transactionResponse->messages` in the response.

I'm not sure the best way to add this functionality, but perhaps adding something like `getTransactionErrorCode` and `getTransactionErrorText` functions that always return those values, regardless of the `isError`.

I can manually work around this for now, just wanted to make a suggestion.

**Comment by stymiee** [comment]
I don't see this as being valuable. There won't be any values contained in those fields that will be unique or otherwise useful. Once you see you the response code (2 is a standard decline, 3 means a voice authorization is required, and 4 means the card needs to be picked up) you know what the status is and can react accordingly. The text in those fields won't be user friendly or unique and you should be creating your own user-friendly messaging in those situations.

**Comment by gRegorLove** [comment]
This was for logging, nothing user-facing. At the moment, I forget the situation that brought this up, though, so it wasn't super important or something I couldn't work around. :)
